package fr.rawz06.rslgenerator.engine.domain.ports;

import fr.rawz06.rslgenerator.engine.domain.entities.Preset;
import fr.rawz06.rslgenerator.engine.domain.entities.SettingsFile;

/**
 * Port for executing the RSL Python script.
 * Abstraction of the random generation script call.
 * Implemented in the API Layer.
 */
public interface RSLScriptRunner {
    /**
     * Executes the Python script to generate RSL settings.
     *
     * @param preset Base preset (RSL or PoT)
     * @return Settings generated by the script
     * @throws ScriptExecutionException If script execution fails
     */
    SettingsFile generateSettings(Preset preset) throws ScriptExecutionException;

    class ScriptExecutionException extends Exception {
        public ScriptExecutionException(String message) {
            super(message);
        }

        public ScriptExecutionException(String message, Throwable cause) {
            super(message, cause);
        }
    }
}
