name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: RawZ06-Studio/.github/.github/workflows/maven-ci-release.yml@main
    with:
      java_version: '25'
    permissions:
      contents: write

  docker:
    needs: release
    uses: RawZ06-Studio/.github/.github/workflows/docker-build-push.yml@main
    permissions:
      contents: write   # Nécessaire pour les tags/releases
      packages: write   # Nécessaire pour Docker/Maven/NPM
    with:
      image_name: rslgenerator
      dokploy_app_id: MzvpF3s4w4k4c1_47ZT11
    secrets: inherit

  snapshot:
    needs: docker
    uses: RawZ06-Studio/.github/.github/workflows/maven-ci-snapshot.yml@main
    with:
      java_version: '25'
    permissions:
      contents: write
